### PR TITLE
multi platform fixes and initial Linux support

### PR DESCRIPTION
**Pull request by davide125**
With this set of commits I'm able to build and run BletchMAME on Linux successfully.

### CODE REVIEW

**Comment by npwoods** [comment]
Nice, I'll take a look at this shortly (not tonight, sorry)

One comment - you're correct that -attach_window is only supported on Windows.  But BletchMAME essentially relies on this functionality to run MAME inside of the BletchMAME window.  Don't we really need the -attach_window functionality implemented for non-Windows platforms in some form?

**Comment by davide125** [comment]
In theory, we should be able to get the same result via the `SDL_WINDOWID` environment variable, but I haven't managed to get it to work yet. I'll put up a PR for it once this is merged so we can iterate on it.

**Comment by davide125** [comment]
According to https://discourse.libsdl.org/t/using-sdl-with-gui-library/19968/14  the `SDL_WINDOWID` hack doesn't work anymore in SDL2 (and in fact I can't find any reference to the variable in SDL's sources), so we might need to go with another approach there. Still even as a separate window for now the UI is usable and useful.

**Comment by npwoods** [comment]
Awesome - I'm surprised (but pleasantly so) that BletchMAME is useful without -attach_window.

Your changes look good - sometime I should set up Github actions to build under Linux so that I can make sure it builds there, and you're not adding random headers in the future.

**Pull request merged**
